name: Inspect ETF Data in DuckDB

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  inspect-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use a compatible Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install duckdb pandas

    - name: Run Database Inspection
      run: python inspect_etf_data.py
