name: Update ETF Data

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  update-etf-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install yfinance duckdb

    - name: Initialize DuckDB
      run: python initialize_duckdb.py

    - name: Migrate JSON to DuckDB
      run: python migrate_to_duckdb.py

    - name: Fetch ETF Data
      run: python fetch_etf_data.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add etf-data.duckdb
        git commit -m "Update ETF historical data" || echo "No changes to commit"
        git push
